[package]
edition = "2021"
name = "model"
version = "0.1.0"

[dependencies]
anyhow = {workspace = true}
dashmap = {workspace = true}
serde = {workspace = true}
serde_bytes = {workspace = true}
serde_repr = "*"
sha3 = {workspace = true}
tokio = {workspace = true}
uuid = {workspace = true}
